plugins:
  - package: 'github.com/qiansheng91/go-instrumentation/plugins/helloworld-plugin'
    path: "../../plugins/tchannel-plugin"
    name: "tchannel-plugin"
    target_packages:
      - packagePath: 'github.com/uber/tchannel-go'
        name: 'tchannel'
        point_cuts:
          - before_advice: 'beforeNewMethod'
            after_advice: 'afterNewMethod'
            target_signature: "NewChannel"