plugins:
  - package: 'github.com/qiansheng91/go-instrumentation/plugins/otel-gin-plugin'
    path: "../../"
    name: "otel-gin-plugin"
    target_packages:
      - packagePath: 'github.com/gin-gonic/gin'
        name: 'gin'
        point_cuts:
          - before_advice: '(*Engine).ServeHTTP'
            after_advice: 'func(*gin.Context)'
            target_signature: "New"