plugins:
  - package: 'github.com/qiansheng91/go-instrumentation/plugins/helloworld-plugin'
    path: "../../plugins/helloworld-plugin"
    name: "helloworld-plugin"
    target_packages:
      - packagePath: 'main'
        name: 'main'
        point_cuts:
          - before_advice: 'beforeNewMethod'
            after_advice: 'afterNewMethod'
            target_signature: "main"